### ISSUE TITLE
Doesn't like Kevin

### ISSUE THREAD

**Issue by kungfu-eric** [intuit/email-decomposer#2]
kevindud@gmail.com will return empty string:

```
EmailDecomposer().decompose(data='kevindud@gmail.com	', get_host=True)
```
{'first_name': '', 'last_name': '', 'host': 'gmail.com\t'}

**Comment by elhanan-mishraky** [comment]
I will check what I can do with it. In the meantime, if you think of a solution feel free to open a PR.

**Comment by elhanan-mishraky** [comment]
What is the desired output here? Is it {'first_name': 'Kevin', 'last_name': 'Dud', 'host': 'gmail.com'}?
