### ISSUE TITLE
First names not in simple emails

### ISSUE THREAD

**Issue by Michael-E-Rose** [intuit/email-decomposer#9]
```
email = "katja.dill@isc.fraunhofer.de"
EmailDecomposer().decompose(data=email, get_host=True)
Out[43]: {'first_name': '', 'last_name': 'Dill', 'host': 'isc.fraunhofer.de'}

email = "stefano.papazian@scilifelab.se"
EmailDecomposer().decompose(data=email, get_host=True)
Out[46]: {'first_name': '', 'last_name': 'Papazian', 'host': 'scilifelab.se'}
```

How come this is neither detecting Katja nor Stefano? I don't believe that neither first name is present in the US Census you use.

**Comment by elhanan-mishraky** [comment]
Hi @Michael-E-Rose, I checked the US Census data and unfortunately it is not there. See [dist.male.first](https://www2.census.gov/topics/genealogy/1990surnames/dist.male.first).
